# Update Ace editor with newest release
name: update_ace

  # Runs every Monday
on:
  schedule:
    - cron: "0 0 * * MON"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: update_ace
    steps:
      - uses: actions/checkout@v2

      - name: Clone the ace repo
        run: git clone https://github.com/ajaxorg/ace-builds.git
        
      - name: Copy and rename files
        run: |
          rm -rf scripts/src/
          mv ace-builds/src-min-noconflict/ scripts/
          cd scripts
          mv src-min-noconflict src
      - name: Commit and push
        run: |
          git add .
          git commit -m "Update ace"
          git push
